### ISSUE TITLE
Error building on Linux Mint

### ISSUE THREAD

**Issue by chookity-pokk** [tchlux/txt_to_html#1]
I am using Linux Mint 19 and tried using the install instruction using `pip3 install https://github.com/tchlux/txt_to_html/archive/1.0.0.zip` both in a virtual environment and outside of it and it gave the error below both times.

```
    error: file '/tmp/pip-qe3805x4-build/util/setup.py' does not exist
    
    ----------------------------------------
Command "/home/hank/Work/GnD/tree/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-qe3805x4-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4bmsdqor-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/hank/Work/GnD/tree/include/site/python3.6/txt-to-html" failed with error code 1 in /tmp/pip-qe3805x4-build/
```

Though running `pip install git+https://github.com/tchlux/txt_to_html.git` worked just fine.

**Comment by tchlux** [comment]
Hey @ragreenburg sorry for the delay. I did an initial investigation on Friday and I think that the 1.0.0.zip version has some accidental references to another of my python packages. I'm in the middle of a significant rewrite of this code and that rewrite is not stable yet, but I expect to have it completed within the next month.

I'll update with my progress on this issue once it is resolved. In the meantime if you want to use the code, I would recommend you pull out the 1.0.0 source and place the contained "txt_to_html" directory somewhere in your Python path. It should work that way.

**Comment by chookity-pokk** [comment]
All is well, thanks for the update and information!

**Comment by tchlux** [comment]
I've pushed the new stable version `1.1.1` and updated the readme. I've tested it on macOS and a clean Ubuntu 20 install, so hopefully it should work on Linux Mint too.

This version will have one important bug fixed from the master branch clone you got before @ragreenburg, I'd suggest updating if you're still interested in using the code.

**Comment by chookity-pokk** [comment]
Thank you!
